openapi: 3.0.0
info:
  version: 0.0.1
  title: Bonds For Success Api
  description: Api outlining the rest calls for the Bonds For Success project

servers:
  - url: localhost:8080

paths:
  /helloWorld:
    get:
      description: Hello World
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /createTable:
    post:
      description: GIVEN a mentee and mentor table THEN return a merged table
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                menteeFile:
                  type: string
                  format: binary
                mentorFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully created merged 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /downloadFile:
    post:
      description: GIVEN an array of matches return into csv
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: File created
          content: 
            text/csv:
              schema:
                type: string
                format: binary
                  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Gender:
      type: string
      enum:
        - Male
        - Female
        - Other
    GenderPreference:
      type: string
      enum:
        - Male
        - Female
        - No Preference
    Match:
      type: object
      properties:
        mentor:
          $ref: '#/components/schemas/Person'
        mentee:
          $ref: '#/components/schemas/Person'
        keywordsShared:
          type: array
          items:
            type: string
          uniqueItems: true
      required:
        - mentor
        - mentee
    Person:
      type: object
      properties:
        name:
          type: string
        emailAddress:
          type: string
        keywords:
          type: array
          items:
            type: string
          uniqueItems: true
        gender:
          $ref: '#/components/schemas/Gender'
        genderPreference:
          $ref: '#/components/schemas/GenderPreference'
      required:
        - name
        - emailAddress
security:
  - BasicAuth: []
