mentee.key.mappings={\
	"\uFEFFWhat is your name?": 'name',\
	"Please enter your Email address.": 'emailAddress',\
	"Is this your first time participating in Bonds for Success?": 'keywords',\
	"Do you identify as:": 'gender',\
    "Would you like to be matched with someone of a specific gender?": 'genderPreference',\
	"What academic institution are you affiliated with?": 'keywords',\
    "What level of education are you working towards?": 'keywords',\
    "What area are you studying?": 'keywords',\
  	"How far along in your education are you?": 'keywords',\
    "What area(s) are you looking to learn more about?": 'keywords',\
    "Do you have a preference on mentor location?": 'keywords',\
    "What workshops do you want to see and/or what do you want to learn from workshops?": 'keywords',\
    "Please briefly explain why you would like to participate in the program. (Approx. five sentences).": 'keywords',\
}

mentor.key.mappings={\
	"\uFEFFWhat is your name?": 'name',\
	"Please enter your Email address.": 'emailAddress',\
	"Is this your first time participating in Bonds for Success?":'keywords',\
	"Do you identify as:": 'gender',\
	"What level of education have you completed? - Selected Choice": 'keywords',\
	"What level of education have you completed? - Graduated Certificate - Text": 'keywords',\
	"Where are you located? - Selected Choice": 'keywords',\
	"Where are you located? - Other - Text":'keywords',\
	"How many mentees are you willing to work with? (minimum 1)": 'keywords',\
	"Would you like to be matched with someone of a specific gender?": 'genderPreference',\
	"Do you have a preference on mentee location?": 'keywords',\
	"How would you like to work with your mentee?": 'keywords',\
	"What area did you study? - Selected Choice": 'keywords',\
	"What area did you study? - Other- Please Specify - Text": 'keywords',\
	"What is/are your area(s) of expertise? - Selected Choice": 'keywords',\
	"What is/are your area(s) of expertise? - Other- Please Specify - Text": 'keywords',\
	"Please expand on your current role and responsibilities in your professional position (brief, 4 sentences max).": 'keywords',\
	"New this year, we are providing industry tours to our mentees. Are you and/or your company interested in facilitating industry tours for our mentees in future cohorts? (This would include a 1-2 hour tour of the facilty and projects on site)":'keywords',\
	"We are hoping to incorportate job shadowing in future cohorts, is this something you would be interested in? (This would include allowing your mentee to spend a day at work with you to experience industry/academia)":'keywords',\
	"Are there any other programs or initiatives you'd like to see Bonds For Success include?":'keywords'\
}

keywords=\
	Doctorate,\
	Master's,\
	Chemical Engineering,\
	Chemistry,\
	Industry,\
	Financial,\
	Managerial,\
	Research and Development,\
	Hiring,\
	Resume,\
	Government,\
	Technical,\
	Entrepreneur,\
	Start-up,\
	Academia,\
	Networking,\
	Alternative,\
	Career,\
	Green,\
	Leadership,\
	Scale up,\
	Transition,\
	Job Seeking,\
	Pharma,\
	Bio,\
	Safety,\
	Process,\
	Analytical,\
	No Preference,\
	Toronto,\
	Kingston,\
	Other,\
	In Person,\
	Online/Email/Zoom,\
	Hybrid

acceptedThreshold=15