mentee.key.mappings={\
	"What is your name?": 'name',\
	"What is your Email address?": 'emailAddress',\
	"Is this your first time participating in Bonds for Success?": 'keywords',\
	"Do you identify as:": 'gender',\
    "Would you like to be matched with someone of a specific gender?": 'genderPreference',\
	"What level of education are you working towards?": 'keywords',\
    "What area are you studying?": 'keywords',\
  	"How far along in your education are you?": 'keywords',\
    "What area(s) are you looking to learn more about?": 'keywords',\
    "Do you have a preference on mentor location?": 'keywords',\
    "What workshops do you want to see and/or what do you want to learn from workshops?": 'keywords',\
    "Please briefly explain why you would like to participate in the program. (Approx. five sentences).": 'keywords'\
}

mentor.key.mappings={\
	"What is your name?": 'name',\
	"Please enter your Email address.": 'emailAddress',\
	"Is this your first time participating in Bonds for Success?":'keywords',\
	"Do you identify as:": 'gender',\
	"Would you like to be matched with someone of a specific gender?": 'genderPreference',\
	"What is your level of education?": 'keywords',\
	"What area did you study?": 'keywords',\
	"What is/are your area(s) of expertise?":'keywords',\
	"Do you have a preference on a mentee location?": 'keywords',\
	"Please expand on your current role and responsibilities in your professional position (brief, 5 sentences max).": 'keywords'\
}

keywords=\
	Doctorate,\
	Master's,\
	Chemical Engineering,\
	Chemistry,\
	Industry,\
	Financial,\
	Managerial,\
	Research and Development,\
	Hiring,\
	Resume,\
	Government,\
	Technical,\
	Entrepreneur,\
	Start-up,\
	Academia,\
	Networking,\
	Alternative,\
	Career,\
	Green,\
	Leadership,\
	Scale up,\
	Transition,\
	Job Seeking,\
	Pharma,\
	Bio,\
	Safety,\
	Process,\
	Analytical,\
	No Preference,\
	Toronto,\
	Kingston,\
	Other,\
	In Person,\
	Online/Email/Zoom,\
	Hybrid

acceptedThreshold=15